// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOHgCQWGSnvtCus9LHv7xbX8OiGKAuAtI',
    appId: '1:601043032951:web:ac2aef65babd7db3e51f72',
    messagingSenderId: '601043032951',
    projectId: 'meditation-c02c0',
    authDomain: 'meditation-c02c0.firebaseapp.com',
    storageBucket: 'meditation-c02c0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChQJmF6Ijixqh5SBtSM7bklphQfHDjb7k',
    appId: '1:601043032951:android:6828d84811e17024e51f72',
    messagingSenderId: '601043032951',
    projectId: 'meditation-c02c0',
    storageBucket: 'meditation-c02c0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKN5oNf381DJsj1vwCoNkGsmtJUDtN5YE',
    appId: '1:601043032951:ios:62dc2295b66701f0e51f72',
    messagingSenderId: '601043032951',
    projectId: 'meditation-c02c0',
    storageBucket: 'meditation-c02c0.appspot.com',
    iosClientId: '601043032951-3ec1urg14cfq0ki1ng1oih3lqm8us2fv.apps.googleusercontent.com',
    iosBundleId: 'com.example.meditation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKN5oNf381DJsj1vwCoNkGsmtJUDtN5YE',
    appId: '1:601043032951:ios:62dc2295b66701f0e51f72',
    messagingSenderId: '601043032951',
    projectId: 'meditation-c02c0',
    storageBucket: 'meditation-c02c0.appspot.com',
    iosClientId: '601043032951-3ec1urg14cfq0ki1ng1oih3lqm8us2fv.apps.googleusercontent.com',
    iosBundleId: 'com.example.meditation',
  );
}
